name: Java CI with Gradle, Kepler-186f


on:
  push:
    branches: [ "features" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: semver
          increment: patch
        env:
          VERSION: "${{ steps.version.outputs.version$-* }}"

      - name: check version
        run: echo "$VERSION"
        
#compile         
      # - name: Setup Gradle
        # uses: gradle/gradle-build-action@v2
      # - name: Run build with Gradle Wrapper
        # run: ./gradlew compileJava

#package


#build

#create docker image taged version


    
#create docker image taged latest


#push images to docker hub


#run image
