name: Java CI with Gradle, Kepler-186f

on:
  push:
    branches: [ "features" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: semver
          increment: patch

      - name: check version
        run: $VERSION="${{ steps.version.outputs.version }}"
        run: echo "${VERSION%-*}"


  

